# Generated by Django 5.1.1 on 2025-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateField(verbose_name='Дата и время публикации')),
                ('location', models.CharField(blank=True, max_length=20, verbose_name='Локация')),
            ],
        ),
    ]
