# Generated by Django 5.1.1 on 2025-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcreate',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_images', verbose_name='Фото'),
        ),
    ]
