# Generated by Django 5.1.1 on 2025-08-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postcreate_pub_date_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCreate',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts_images', verbose_name='Фото'),
        ),
    ]
